In [7]:

import pandas as pd

e = pd.read_csv(r'/Users/vjaishnav/Desktop/Fitness_Data.csv')
e = e.reset_index()
m = e
m.drop(m.columns[[1]], axis=1, inplace=True)
m

,level_0,level_2,level_3,level_4,level_5,level_6,Fitness_Data from 2023-01-01 to 2023-11-17
0,Date,Active Energy (kcal),Heart Rate [Min] (bpm),Heart Rate [Max] (bpm),Heart Rate [Avg] (bpm),Step Count (steps),Walking + Running Distance (mi)
1,2023-01-01 00:00:00,471.64,40,169,70.49,8507,4.52
2,2023-01-02 00:00:00,380.09,45,126,64.69,7159,3.55
3,2023-01-03 00:00:00,235.22,48,138,62.27,3667,1.83
4,2023-01-04 00:00:00,20.09,53,76,63.51,2297,0.93
...,...,...,...,...,...,...,...
317,2023-11-13 00:00:00,396.36,43,118,61.6,5661,2.43
318,2023-11-14 00:00:00,228.81,42,116,53.93,3520,1.58
319,2023-11-15 00:00:00,344.65,46,114,60.77,4448,2
320,2023-11-16 00:00:00,234.87,45,112,60.09,7064,2.91
321,2023-11-17 00:00:00,410.8,45,120,63.64,5711,2.46